name: SwiftUI-DevRecipes
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: en
  # postGenCommand: rbenv exec bundle exec pod install  

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  Drawing:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.example.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"Drawing/Resources/Preview Content\""
    sources:
      - path: Drawing
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh
  PhotoFilter:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.example.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"PhotoFilter/Resources/Preview Content\""
    sources:
      - path: PhotoFilter
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh        

schemes:
  Drawing:
    build:
      targets:
        Drawing: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug
  PhotoFilter:
    build:
      targets:
        PhotoFilter: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug      