name: SwiftUI-DevRecipes
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: en
  # postGenCommand: rbenv exec bundle exec pod install  

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  Drawing:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.example.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"$TARGET_NAME/Resources/Preview Content\""
    sources:
      - path: Drawing
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh
  PhotoFilter:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.example.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"$TARGET_NAME/Resources/Preview Content\""
    sources:
      - path: PhotoFilter
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh
  TodoReminder:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.example.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"$TARGET_NAME/Resources/Preview Content\""
        DEVELOPMENT_TEAM: 8AG5PV5JZM
        CODE_SIGN_ENTITLEMENTS: $TARGET_NAME/Resources/TodoReminder.entitlements
    sources:
      - path: TodoReminder
      - path: TodoReminderShared
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh
    dependencies:
      - target: TodoReminderWidget
  TodoReminderWidget:
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.example.TodoReminder.Widget
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"$TARGET_NAME/Resources/Preview Content\""
        DEVELOPMENT_TEAM: 8AG5PV5JZM
        CODE_SIGN_ENTITLEMENTS: $TARGET_NAME/Resources/TodoReminder.entitlements
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground        
    sources:
      - path: TodoReminderWidget
      - path: TodoReminderShared
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework      
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh

schemes:
  Drawing:
    build:
      targets:
        Drawing: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Release
  PhotoFilter:
    build:
      targets:
        PhotoFilter: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Release
  TodoReminder:
    build:
      targets:
        TodoReminder: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release